[package]
name = "wvw-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { workspace =  true, features = ["fs"] }
tracing.workspace = true
tracing_subscriber.workspace = true
